// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nOQOPOOOOOO'#C^'#C^O!_OPO'#C^QOOOOOOOOO,58x,58x",
  stateData: "#f~OSQOTQOUPOVPOWPOXPOYPOZPO[PO]PO^PO_PO`POaPObPOcPOdPOePOfPO~OUSOVSOWSOXSOYSOZSO[SO]SO^SO_SO`SOaSObSOcSOdSOeSOfSO~O",
  goto: "VRPPSRRO",
  nodeNames: "⚠ Program Keyword",
  maxTerm: 22,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: ",X~RZYZtpqy#T#U!O#X#Y!g#^#_#W#`#a#i#a#b$j#c#d%X#f#g&|#h#i'}#j#k*^~yOT~~!OOS~~!RP#b#c!U~!XP#b#c![~!_P#T#U!b~!gOf~~!jP#h#i!m~!rPW~#X#Y!u~!xP#X#Y!{~#OP#b#c#R~#WOV~~#ZP#c#d#^~#aP#g#h#d~#iO_~~#lP#i#j#o~#rP#j#k#u~#xP#i#j#{~$OP#]#^$R~$UP#`#a$X~$[P#`#a$_~$bP#X#Y$e~$jOe~~$mP#]#^$p~$sP#h#i$v~$yP#X#Y$|~%PP#b#c%S~%XOb~~%[Q#]#^%b#`#a&_~%gP^~#_#`%j~%mP#X#Y%p~%sP#T#U%v~%yP#`#a%|~&PP#`#a&S~&VP#X#Y&Y~&_O]~~&bP#_#`&e~&hP#c#d&k~&nP#c#d&q~&tP#b#c&w~&|Oa~~'PP#]#^'S~'VP#]#^'Y~']P#d#e'`~'cP#d#e'f~'iP#i#j'l~'oP#X#Y'r~'uP#b#c'x~'}O`~~(QR#T#U(Z#c#d(z#i#j)i~(`PY~#T#U(c~(fP#_#`(i~(lP#g#h(o~(rP#X#Y(u~(zOX~~(}P#]#^)Q~)TP#g#h)W~)ZP#h#i)^~)aP#T#U)d~)iOd~~)lP#`#a)o~)rP#c#d)u~)xP#g#h){~*OP#h#i*R~*UP#T#U*X~*^OU~~*aP#T#U*d~*iQ[~#`#a*o#g#h+W~*rP#a#b*u~*xP#]#^*{~+OP#g#h+R~+WOc~~+ZP#X#Y+^~+aP#a#b+d~+gP#a#b+j~+mP#T#U+p~+sP#`#a+v~+yP#`#a+|~,PP#X#Y,S~,XOZ~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
