export default {
    searchPlaceholder: "Search Command",
    commandListTitle: "Commands",
    command: {
        anna: "output",
        et: "fd",
        eteen: "forward",
        jos: "if",
        luvuille: "for",
        miten: "to",
        oi: "rt",
        oikealle: "right",
        olkoon: "make",
        riippuen: "ifelse",
        ta: "bk",
        taakse: "backward",
        toista: "repeat",
        tulosta: "show",
        va: "lt",
        valmis: "end",
        vasemmalle: "left",
    },
    returnbutton: "Return",
    editorPlaceholder: "Write code here",
    navbar: "Code Editor",
    editorView: {
        writeCode: "Write code:",
        sendToCompilerBtn: "Send code to compiler",
        sendToRobotBtn: "Send code to robot",
    },
    response: {
        serverResponded: "Server responded:",
        line: "line:",
        start: "start:",
        end: "end:",
        message: "message:",
    }
};