export default {
    searchPlaceholder: "Search Command",
    commandListTitle: "Commands",
    command: {
        anna: "output",
        et: "fd",
        eteen: "forward",
        jos: "if",
        luvuille: "for",
        miten: "to",
        oi: "rt",
        oikealle: "right",
        olkoon: "make",
        riippuen: "ifelse",
        ta: "bk",
        taakse: "backward",
        toista: "repeat",
        tulosta: "show",
        va: "lt",
        valmis: "end",
        vasemmalle: "left",
    },
    returnbutton: "Return",
    editorPlaceholder: "Write code here",
    navbar: {
        title: "Code Editor",
        login: 'Log in',
        loggedInAs: 'Logged in as: ',
        logOut: 'Log out'

    },
    editorView: {
        writeCode: "Write code:",
        sendToCompilerBtn: "Send code to compiler",
        sendToRobotBtn: "Send code to robot",
    },
    response: {
        serverResponded: "Server responded:",
        line: "line:",
        start: "start:",
        end: "end:",
        message: "message:",
        confirmation: "Sent to compiler!",
    },
    login: {
        title: 'Your name',
        loginButton: 'Log in',
        nameInputPlaceholder: 'name',
        notificationNameMissing: 'You can\'t login without a name!',
    },
    editorNavbar: {
        chooseFile: 'Choose File',
        fileName: 'File',
        createdAt: 'Created at',
        lastEdited: 'Last edited',
        newFile: 'New File',
        saveFile: 'Save',
        filenamePlaceholder: 'Enter a new filename',
        saveWithName: 'Save as',
        openFile: 'Open File',
        file: 'File: ',
        open: 'Open',
        delete: 'Delete',
        confirmDeleteMessage: 'Are you sure you want to delete the file: {filename} ?'
    },
    adminView:{
        adminDashboard: 'Admin Dashboard',
        userManagement: 'User Management',
        back: 'Back',
        showFiles:'Show Files',
        showUserInfo:'Show User Info',
        searchUser:'Search user...',
        username:'Username:',
        password:'Password:',
        deleteUser:'Delete User',
        noUserFilesFound:'No files found for this user.',
        noFilesFound:'No files found',
        allFiles:'All Files',
        upload:'Upload',
        download:'Download',
        save:'Save',
        delete:'Delete',
        info:'Info',
        files:'Files',
        creator:'Creator: ',
        changePassword:'Change password',
        chooseOwner: 'Choose owner',
        chooseUser: 'Choose user',
        piilota: 'Hide',
        restore: 'Restore'
    },
    tooltipOpenSidebar: "Click word to display on sidebar",
    toggleLanguage: 'Vaihda Suomeksi'
};