export default {
    searchPlaceholder: "Etsi käskyä",
    commandListTitle: "Käskyt",
    command: {
        anna: "anna",
        et: "et",
        eteen: "eteen",
        jos: "jos",
        luvuille: "luvuille",
        miten: "miten",
        oi: "oi",
        oikealle: "oikealle",
        olkoon: "olkoon",
        riippuen: "riippuen",
        ta: "ta",
        taakse: "taakse",
        toista: "toista",
        tulosta: "tulosta",
        va: "va",
        valmis: "valmis",
        vasemmalle: "vasemmalle",
    },
    returnbutton: "Takaisin",
    editorPlaceholder: "Kirjoita koodia tähän",
    navbar: "Koodieditori",
    editorView: {
        writeCode: "Kirjoita koodia:",
        sendToCompilerBtn: "Lähetä koodi kääntäjälle",
        sendToRobotBtn: "Lähetä koodi robotille",
    },
    response: {
        serverResponded: "Palvelin vastasi:",
        line: "rivi:",
        start: "alku:",
        end: "loppu:",
        message: "viesti:",
    }
};
